platform :ios, '13.0'
use_frameworks! :linkage => :static

target 'live-video-clean' do
  use_expo_modules!

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'EXPO_MODULES_HEADER_SEARCH_PATHS="${PODS_ROOT}/Headers/Public"'
      end
    end
  end
end
